blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/Hari-Skr/Hari-Skr/discussions
    about: Use Discussions for questions, ideas, and general conversation.
